OPT_PARAM_CHOICES = [
    ('assists', 'Assists'),
    ('bonus', 'Bonus Points'),
    ('bps', 'BPS'),
    ('creativity', 'Creativity'),
    ('ep_next', 'xP (Next GW)'),
    ('ep_this', 'xP (Last GW)'),
    ('form', 'Form'),
    ('goals_scored', 'Goals Scored'),
    ('ict_index', 'ICT Index'),
    ('influence', 'Influence'),
    ('event_points', 'Points (Last GW)'),
    ('minutes', 'Mins Played'),
    ('points_per_game', 'Points/Game'),
    ('cost_change_event', 'Price Changes'),
    ('selected_by_percent', 'Selected By %'),
    ('threat', 'Threat'),
    ('dreamteam_count', 'Dreamteam Count'),
    ('total_points', 'Total Points'),
    ('transfers_in_event', 'Transfers in GW'),
    ('transfers_in', 'Transfers in Total'),
    ('value_form', 'Value Form'),
    ('value_season', 'Value Season'),
]