# Generated by Django 2.2.5 on 2019-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191008_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
