# Generated by Django 2.2.5 on 2019-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191008_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(default='', max_length=3)),
                ('team_code', models.CharField(default='', max_length=3)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
