# Generated by Django 2.2.5 on 2019-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191013_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='next_game_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='next_game_team',
            field=models.CharField(default='', max_length=50),
        ),
    ]
