# Generated by Django 2.2.5 on 2019-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191029_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='next_game_team',
            new_name='next_game_team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='next_game_team_id',
            field=models.IntegerField(default=0),
        ),
    ]
