# Generated by Django 2.2.5 on 2019-11-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191029_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opt_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
