# Generated by Django 2.2.5 on 2019-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_player_opt_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_raw',
            field=models.CharField(default='', max_length=200),
        ),
    ]
