# Generated by Django 2.2.5 on 2019-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_player_name_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name_short',
            field=models.CharField(default='', max_length=3),
        ),
    ]
