# Generated by Django 2.2.5 on 2019-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_team_team_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name_short',
            field=models.CharField(default='', max_length=3),
        ),
    ]
