# Generated by Django 2.2.5 on 2020-02-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200102_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('sim_type', models.IntegerField()),
                ('opt_param', models.CharField(max_length=64)),
                ('n_subs', models.IntegerField(blank=True, default=0)),
                ('include', models.CharField(blank=True, default='', max_length=1000)),
                ('exclude', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
