# Generated by Django 2.2.5 on 2020-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='date_time',
        ),
        migrations.AddField(
            model_name='usage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
