# Generated by Django 2.2.5 on 2020-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200212_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='exclude',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='include',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='n_subs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
