# Generated by Django 2.2.5 on 2020-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200304_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='XgLookup',
            fields=[
                ('player_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('xg_name', models.CharField(default='', max_length=200)),
                ('xg_team', models.CharField(default='', max_length=200)),
                ('xg_season', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
